export default [
    {
        "name": "ゼレンスラプヨン",
        "lv": "4",
        "hp": "215",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "オーグル",
        "lv": "5",
        "hp": "178",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "キッズプライム",
        "lv": "5",
        "hp": "168",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "ミニプライム",
        "lv": "5",
        "hp": "171",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "シャロン",
        "lv": "5",
        "hp": "271",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原西"
    },
    {
        "name": "シャルット",
        "lv": "5",
        "hp": "271",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原西"
    },
    {
        "name": "チビプヨン",
        "lv": "6",
        "hp": "198",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "グリンチビプヨン",
        "lv": "6",
        "hp": "185",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "ジャイアントチビプヨン",
        "lv": "6",
        "hp": "330",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "怒ヨン",
        "lv": "6",
        "hp": "27067",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "▲",
        "wind": "",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "コッパオーグル",
        "lv": "7",
        "hp": "367",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "プヨプライム",
        "lv": "7",
        "hp": "968",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "ヴァルッドシオス",
        "lv": "7",
        "hp": "1346",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "警備オーグル",
        "lv": "8",
        "hp": "490",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原西"
    },
    {
        "name": "ドロップヨン",
        "lv": "1",
        "hp": "165",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "旅立ちの草原"
    },
    {
        "name": "グリンスラプヨン",
        "lv": "2",
        "hp": "194",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "旅立ちの草原"
    },
    {
        "name": "シャロン",
        "lv": "3",
        "hp": "228",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "旅立ちの草原"
    },
    {
        "name": "グリンスラプヨン",
        "lv": "3",
        "hp": "228",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "旅立ちの草原"
    },
    {
        "name": "ゼレンスラプヨン",
        "lv": "3",
        "hp": "228",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "旅立ちの草原"
    },
    {
        "name": "スラプヨン",
        "lv": "1",
        "hp": "90",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "冒険者の修練所"
    },
    {
        "name": "スラプヨン",
        "lv": "2",
        "hp": "125",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "冒険者の修練所"
    },
    {
        "name": "シュカル",
        "lv": "3",
        "hp": "155",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "グリンスラプヨン",
        "lv": "4",
        "hp": "186",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "冒険者の修練所"
    },
    {
        "name": "マインドシュカル",
        "lv": "4",
        "hp": "204",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "アレンドシュカル",
        "lv": "4",
        "hp": "204",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "マインドシュカル",
        "lv": "5",
        "hp": "246",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "衛兵シュカル",
        "lv": "5",
        "hp": "246",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "バッサー",
        "lv": "5",
        "hp": "197",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "冒険者の修練所"
    },
    {
        "name": "レッサーカロック",
        "lv": "5",
        "hp": "246",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "冒険者の修練所"
    },
    {
        "name": "亡霊剣士",
        "lv": "5",
        "hp": "315",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "冒険者の修練所"
    },
    {
        "name": "薄皮のツツム",
        "lv": "1",
        "hp": "4500000",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "暴走プヨン",
        "lv": "5",
        "hp": "360",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "クリムスラプ",
        "lv": "6",
        "hp": "468",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "プラトーローズン",
        "lv": "6",
        "hp": "1141.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "クリムスラプ",
        "lv": "7",
        "hp": "550.5",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "クリムスラプハード",
        "lv": "7",
        "hp": "783",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "ローズン",
        "lv": "7",
        "hp": "550.5",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "キッズベルーヌ",
        "lv": "7",
        "hp": "550.5",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "マインドシュカル",
        "lv": "7",
        "hp": "550.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "クリムスラプ",
        "lv": "8",
        "hp": "792",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "▲",
        "wind": "○",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "マインドシュカル",
        "lv": "8",
        "hp": "727.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "スリールシュカル",
        "lv": "8",
        "hp": "792",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "秘密のマインドシュカル",
        "lv": "8",
        "hp": "540",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "ホーミングシュカル",
        "lv": "8",
        "hp": "907.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "青ピン",
        "lv": "8",
        "hp": "2664",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "怒ヨン",
        "lv": "8",
        "hp": "93940.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "▲",
        "wind": "",
        "shine": "▲",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "プヨンマイム",
        "lv": "9",
        "hp": "951",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "▲",
        "dark": "○",
        "area": "アテーリア草原東"
    },
    {
        "name": "ローズン",
        "lv": "9",
        "hp": "907.5",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "メアレコット",
        "lv": "9",
        "hp": "907.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア草原東"
    },
    {
        "name": "オーグル",
        "lv": "9",
        "hp": "907.5",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "ハイオーグル",
        "lv": "9",
        "hp": "907.5",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "マインドシュカル",
        "lv": "9",
        "hp": "907.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原東"
    },
    {
        "name": "オーグル",
        "lv": "10",
        "hp": "1086",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "ハイオーグル",
        "lv": "10",
        "hp": "1086",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "負傷したハイオーグル",
        "lv": "10",
        "hp": "810",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "セアンベルーヌ",
        "lv": "10",
        "hp": "4341",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "ローズン",
        "lv": "12",
        "hp": "1771.5",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原東"
    },
    {
        "name": "フィアスウモー",
        "lv": "12",
        "hp": "1771.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア草原東"
    },
    {
        "name": "オーグル",
        "lv": "12",
        "hp": "1771.5",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "ハイオーグル",
        "lv": "12",
        "hp": "1771.5",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "オルーグニック",
        "lv": "15",
        "hp": "40435.5",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "バロニアレコット",
        "lv": "15",
        "hp": "22579.5",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア草原東"
    },
    {
        "name": "ハンマーイッサス",
        "lv": "20",
        "hp": "9540",
        "physics": "▲",
        "devil": "◎",
        "ground": "×",
        "water": "◎",
        "fire": "◎",
        "wind": "◎",
        "shine": "○",
        "dark": "",
        "area": "アテーリア草原東"
    },
    {
        "name": "プヨンマイム",
        "lv": "1",
        "hp": "138",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "▲",
        "dark": "○",
        "area": "清めの間"
    },
    {
        "name": "シャロンプラトー",
        "lv": "3",
        "hp": "174",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "清めの間"
    },
    {
        "name": "ルインズアイ",
        "lv": "8",
        "hp": "1056",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "清めの間"
    },
    {
        "name": "メアプヨン",
        "lv": "9",
        "hp": "1188",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "清めの間"
    },
    {
        "name": "ラニーアイ",
        "lv": "10",
        "hp": "1448",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "清めの間"
    },
    {
        "name": "ウモー",
        "lv": "12",
        "hp": "2362",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "清めの間"
    },
    {
        "name": "グリムモンク",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムマジックナイト",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムガーディアン",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムアサシン",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムビショップ",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムウォーロック",
        "lv": "12",
        "hp": "2480",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "グリムサーチャー",
        "lv": "12",
        "hp": "2362",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "清めの間"
    },
    {
        "name": "プヨンマイム",
        "lv": "4",
        "hp": "270",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "▲",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "コートイグニス",
        "lv": "4",
        "hp": "218",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "×",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "ダルスビープ",
        "lv": "4",
        "hp": "190",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "サイレントスビープ",
        "lv": "8",
        "hp": "496",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "プルージェリー",
        "lv": "8",
        "hp": "484",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "フォレストローズン",
        "lv": "9",
        "hp": "554",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原北"
    },
    {
        "name": "バラススビープ",
        "lv": "9",
        "hp": "572",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "プループリリン",
        "lv": "10",
        "hp": "663",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "シャロンプラトー",
        "lv": "11",
        "hp": "961",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原北"
    },
    {
        "name": "リトルイグニス",
        "lv": "11",
        "hp": "1078",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "×",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "スコーチイグニス",
        "lv": "11",
        "hp": "1430",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "×",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "プヨンマイム",
        "lv": "11",
        "hp": "898",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "▲",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "シェフレラ",
        "lv": "11",
        "hp": "938",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "アテーリア草原北"
    },
    {
        "name": "ファイアーアイ",
        "lv": "11",
        "hp": "941",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "サンダーアイ",
        "lv": "11",
        "hp": "941",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "フロストアイ",
        "lv": "11",
        "hp": "1882",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "ピルッツ",
        "lv": "12",
        "hp": "1043",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "",
        "fire": "○",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原北"
    },
    {
        "name": "陽気な菌類",
        "lv": "12",
        "hp": "2685",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "",
        "fire": "○",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア草原北"
    },
    {
        "name": "グリンジェリー",
        "lv": "13",
        "hp": "1175",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "バーミアイ",
        "lv": "13",
        "hp": "669",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "腹ペコイグニス",
        "lv": "13",
        "hp": "3828",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "◎",
        "fire": "×",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "リチュアルバッサー",
        "lv": "13",
        "hp": "2902",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア草原北"
    },
    {
        "name": "準女王蜂",
        "lv": "14",
        "hp": "5990",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "アテーリア草原北"
    },
    {
        "name": "サンゲイザー",
        "lv": "14",
        "hp": "7788",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア草原北"
    },
    {
        "name": "ヴォンカルツァー",
        "lv": "10",
        "hp": "6272",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "エルトス大城壁"
    },
    {
        "name": "スラプヨン(LL)",
        "lv": "13",
        "hp": "20000",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "アイシックオーグルガード",
        "lv": "14",
        "hp": "3300",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "グローブシャルット",
        "lv": "14",
        "hp": "3948",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "エルトス大城壁"
    },
    {
        "name": "フォレストスネイル",
        "lv": "14",
        "hp": "5000",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "アイシックオーグルガード",
        "lv": "15",
        "hp": "3650",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "マグーナオーグル",
        "lv": "15",
        "hp": "3650",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "黄昏の凶鳥",
        "lv": "15",
        "hp": "21632",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "エルトス大城壁"
    },
    {
        "name": "フォレストスネイル",
        "lv": "15",
        "hp": "5250",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "シックアイサージェント",
        "lv": "16",
        "hp": "33304",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "アイシックオーグルチーフ",
        "lv": "17",
        "hp": "4550",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルトス大城壁"
    },
    {
        "name": "ヒュージスネイル",
        "lv": "14",
        "hp": "5922",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "ライオットオーグル",
        "lv": "15",
        "hp": "3932",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "シェルスビープ",
        "lv": "15",
        "hp": "4324",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "コルキア平原"
    },
    {
        "name": "グローブシャルット",
        "lv": "16",
        "hp": "4430",
        "physics": "",
        "devil": "",
        "ground": "×",
        "water": "",
        "fire": "○",
        "wind": "×",
        "shine": "×",
        "dark": "◎",
        "area": "コルキア平原"
    },
    {
        "name": "グローブプヨン",
        "lv": "16",
        "hp": "4430",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "シェルスビープ",
        "lv": "16",
        "hp": "4524",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "○",
        "fire": "○",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "コルキア平原"
    },
    {
        "name": "デスメロン",
        "lv": "16",
        "hp": "14000",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "ガーススネイル",
        "lv": "18",
        "hp": "6000",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "コルキアンガルグ",
        "lv": "19",
        "hp": "6006",
        "physics": "",
        "devil": "◎",
        "ground": "",
        "water": "○",
        "fire": "○",
        "wind": "○",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "ミスリルマイマイ",
        "lv": "19",
        "hp": "28000",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "コルキアンガルグ",
        "lv": "20",
        "hp": "5802",
        "physics": "",
        "devil": "◎",
        "ground": "",
        "water": "○",
        "fire": "○",
        "wind": "○",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "ガーススネイル",
        "lv": "20",
        "hp": "6500",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "イッサス",
        "lv": "20",
        "hp": "14000",
        "physics": "▲",
        "devil": "◎",
        "ground": "×",
        "water": "◎",
        "fire": "◎",
        "wind": "◎",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "メテオゴースト",
        "lv": "21",
        "hp": "7086",
        "physics": "▲",
        "devil": "▲",
        "ground": "▲",
        "water": "◎",
        "fire": "×",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "コルキア平原"
    },
    {
        "name": "ハイコルキアンガルグ",
        "lv": "21",
        "hp": "6442",
        "physics": "",
        "devil": "◎",
        "ground": "",
        "water": "○",
        "fire": "○",
        "wind": "○",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "チーフブルーガ",
        "lv": "21",
        "hp": "76204",
        "physics": "",
        "devil": "◎",
        "ground": "",
        "water": "○",
        "fire": "○",
        "wind": "○",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "双刃の略奪者",
        "lv": "21",
        "hp": "17172",
        "physics": "",
        "devil": "◎",
        "ground": "",
        "water": "○",
        "fire": "○",
        "wind": "○",
        "shine": "○",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "竜のため息",
        "lv": "22",
        "hp": "37520",
        "physics": "▲",
        "devil": "▲",
        "ground": "▲",
        "water": "◎",
        "fire": "×",
        "wind": "▲",
        "shine": "",
        "dark": "○",
        "area": "コルキア平原"
    },
    {
        "name": "朴訥巨人ピエール",
        "lv": "30",
        "hp": "2000000",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "コルキア平原"
    },
    {
        "name": "オーグル",
        "lv": "1",
        "hp": "260",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "カロック",
        "lv": "10",
        "hp": "1568",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "レードルシュカル",
        "lv": "11",
        "hp": "2340",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "煙霞のシュカル",
        "lv": "11",
        "hp": "2340",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "バリエリーアイ",
        "lv": "12",
        "hp": "2558",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "レッシュアイ",
        "lv": "12",
        "hp": "2558",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "レードルシュカル",
        "lv": "13",
        "hp": "2902",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "煙霞のシュカル",
        "lv": "13",
        "hp": "3482",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "獄囚オーグル",
        "lv": "13",
        "hp": "2902",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "バリエリーアイ",
        "lv": "14",
        "hp": "3170",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "レッシュアイ",
        "lv": "14",
        "hp": "3934",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ミスブローアイ",
        "lv": "15",
        "hp": "4014",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ティラリーアイ",
        "lv": "15",
        "hp": "4014",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ドリーカロック",
        "lv": "15",
        "hp": "4014",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "煙霞のシュカル",
        "lv": "15",
        "hp": "4014",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "獄囚ハイオーグル",
        "lv": "15",
        "hp": "3650",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ミスブローアイ",
        "lv": "16",
        "hp": "4202",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "トイスカロック",
        "lv": "16",
        "hp": "4202",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ホルツシュカル",
        "lv": "16",
        "hp": "4202",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "バダルシュカル",
        "lv": "16",
        "hp": "4202",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ホルツシュカル",
        "lv": "17",
        "hp": "4648",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "バダルシュカル",
        "lv": "17",
        "hp": "4648",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "獄囚レラオーグル",
        "lv": "17",
        "hp": "4648",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ミスブローアイ",
        "lv": "18",
        "hp": "4834",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ティラリーアイ",
        "lv": "18",
        "hp": "4834",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "フォラグカロック",
        "lv": "18",
        "hp": "4834",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ホルツシュカル",
        "lv": "18",
        "hp": "4834",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "バダルシュカル",
        "lv": "18",
        "hp": "4834",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ペトラロングヌス",
        "lv": "18",
        "hp": "85862",
        "physics": "▲",
        "devil": "◎",
        "ground": "×",
        "water": "◎",
        "fire": "◎",
        "wind": "◎",
        "shine": "○",
        "dark": "",
        "area": "アテーリア東兵舎跡"
    },
    {
        "name": "ウモー",
        "lv": "13",
        "hp": "3348",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "フィアスウモー",
        "lv": "13",
        "hp": "3348",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "アスターオーグル",
        "lv": "13",
        "hp": "3348",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ウモー",
        "lv": "14",
        "hp": "3658",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "フィアスウモー",
        "lv": "14",
        "hp": "4540",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "イービルアイ",
        "lv": "14",
        "hp": "3658",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "リシャスアイ",
        "lv": "14",
        "hp": "4540",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "アスターオーグル",
        "lv": "15",
        "hp": "4212",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "アスターオーグル",
        "lv": "16",
        "hp": "4746",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ポイズンボックス",
        "lv": "16",
        "hp": "4848",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ヴェレーノボックス",
        "lv": "16",
        "hp": "4848",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "イービルアイ",
        "lv": "16",
        "hp": "4746",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "マグーナオーグル",
        "lv": "17",
        "hp": "5250",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ポイズンボックス",
        "lv": "17",
        "hp": "5364",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ヴェレーノボックス",
        "lv": "17",
        "hp": "5364",
        "physics": "",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "○",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ナイトバード",
        "lv": "18",
        "hp": "5070",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ステラーバード",
        "lv": "18",
        "hp": "5070",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "マグーナオーグル",
        "lv": "18",
        "hp": "5070",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "リシャスアイ",
        "lv": "18",
        "hp": "5070",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ガードアイ",
        "lv": "20",
        "hp": "6216",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ゴライッサス",
        "lv": "20",
        "hp": "15876",
        "physics": "▲",
        "devil": "◎",
        "ground": "×",
        "water": "◎",
        "fire": "◎",
        "wind": "◎",
        "shine": "○",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ギガライッサス",
        "lv": "20",
        "hp": "15876",
        "physics": "▲",
        "devil": "◎",
        "ground": "×",
        "water": "◎",
        "fire": "◎",
        "wind": "◎",
        "shine": "○",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "オプティアンガード",
        "lv": "21",
        "hp": "6904",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ナイトバード",
        "lv": "22",
        "hp": "7140",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "イヴィックオーグル",
        "lv": "22",
        "hp": "7140",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ガードアイ",
        "lv": "23",
        "hp": "10000",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "オプティアンガード",
        "lv": "23",
        "hp": "13000",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ナイトバード",
        "lv": "24",
        "hp": "8146",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ステラーバード",
        "lv": "24",
        "hp": "8146",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ディルクオーグル",
        "lv": "24",
        "hp": "8146",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "イヴィックオーグル",
        "lv": "25",
        "hp": "8416",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "キングウモー",
        "lv": "25",
        "hp": "240576",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ディルクオーグル",
        "lv": "27",
        "hp": "13000",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "ジルディアリクス",
        "lv": "30",
        "hp": "636000",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "ヴェルク遺跡"
    },
    {
        "name": "アレンドシュカル",
        "lv": "5",
        "hp": "542",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "フィアスバッサー",
        "lv": "6",
        "hp": "580",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "リトルバッサー",
        "lv": "6",
        "hp": "464",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "ハンターアイ",
        "lv": "6",
        "hp": "580",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "フィアスバッサー",
        "lv": "8",
        "hp": "968",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "ステラーバッサー",
        "lv": "8",
        "hp": "968",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "○",
        "dark": "▲",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "マインドシュカル",
        "lv": "10",
        "hp": "1326",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア地下迷路"
    },
    {
        "name": "ソルシュカル",
        "lv": "10",
        "hp": "1326",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "アテーリア地下迷路"
    }, {
        "name": "ブルウジェリー",
        "lv": "8",
        "hp": "1144",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "プヨプリリン",
        "lv": "9",
        "hp": "1310",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ブルウプリリン",
        "lv": "10",
        "hp": "1568",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "エアルシュカル",
        "lv": "10",
        "hp": "1568",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "レイバシュカル",
        "lv": "13",
        "hp": "2902",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ルバックガルグ",
        "lv": "14",
        "hp": "3934",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "クリムゾンアイ",
        "lv": "14",
        "hp": "3170",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "シュカルソードマン",
        "lv": "14",
        "hp": "3784",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ビーモ",
        "lv": "14",
        "hp": "3170",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "",
        "dark": "▲",
        "area": "エルロンド地下水路"
    },
    {
        "name": "フラビーモ",
        "lv": "14",
        "hp": "3170",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "",
        "dark": "▲",
        "area": "エルロンド地下水路"
    },
    {
        "name": "グリースビーモ",
        "lv": "15",
        "hp": "3650",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "",
        "dark": "▲",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ゼレンジェリー",
        "lv": "15",
        "hp": "3650",
        "physics": "○",
        "devil": "▲",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ベラットガルグ",
        "lv": "16",
        "hp": "4114",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "フィラスビーモ",
        "lv": "16",
        "hp": "4114",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "×",
        "shine": "",
        "dark": "▲",
        "area": "エルロンド地下水路"
    },
    {
        "name": "レルードガルグ",
        "lv": "17",
        "hp": "4648",
        "physics": "▲",
        "devil": "",
        "ground": "",
        "water": "○",
        "fire": "",
        "wind": "",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "スカレットアイ",
        "lv": "17",
        "hp": "4550",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ブロッソアイ",
        "lv": "18",
        "hp": "4834",
        "physics": "○",
        "devil": "×",
        "ground": "×",
        "water": "×",
        "fire": "×",
        "wind": "×",
        "shine": "",
        "dark": "",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ストームシューデル",
        "lv": "18",
        "hp": "9672",
        "physics": "▲",
        "devil": "▲",
        "ground": "◎",
        "water": "▲",
        "fire": "▲",
        "wind": "×",
        "shine": "",
        "dark": "○",
        "area": "エルロンド地下水路"
    },
    {
        "name": "酔狂のシュカル",
        "lv": "18",
        "hp": "10732",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "エルロンド地下水路"
    },
    {
        "name": "遺忘衛士",
        "lv": "18",
        "hp": "42932",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "エルロンド地下水路"
    },
    {
        "name": "ヤドゥカ",
        "lv": "14",
        "hp": "8460",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "×",
        "fire": "◎",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "リッパヤドゥカ",
        "lv": "17",
        "hp": "10728",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "×",
        "fire": "◎",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "リークゲシュタ",
        "lv": "23",
        "hp": "15672",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "ヤドゥカマイスター",
        "lv": "26",
        "hp": "113400",
        "physics": "",
        "devil": "",
        "ground": "▲",
        "water": "×",
        "fire": "◎",
        "wind": "○",
        "shine": "",
        "dark": "",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "キャバルゲシュタ",
        "lv": "27",
        "hp": "25488",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "ケイヴジャーク",
        "lv": "28",
        "hp": "43200",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "▲",
        "fire": "○",
        "wind": "○",
        "shine": "",
        "dark": "▲",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "亡霊ヒュンデバルト",
        "lv": "29",
        "hp": "121260",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "",
        "fire": "",
        "wind": "",
        "shine": "◎",
        "dark": "×",
        "area": "イヴワール鍾乳洞"
    },
    {
        "name": "水竜アクアレウス",
        "lv": "30",
        "hp": "1107264",
        "physics": "",
        "devil": "",
        "ground": "",
        "water": "×",
        "fire": "○",
        "wind": "◎",
        "shine": "",
        "dark": "",
        "area": "イヴワール鍾乳洞"
    },
    { "name": "プヨンマイム", "lv": "12", "hp": "4491", "physics": "", "devil": "", "ground": "", "water": "▲", "fire": "", "wind": "○", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "プヨンマイムフロスト", "lv": "12", "hp": "4230", "physics": "", "devil": "", "ground": "", "water": "▲", "fire": "", "wind": "○", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "アイスマッフル", "lv": "24", "hp": "13500", "physics": "", "devil": "", "ground": "", "water": "◎", "fire": "×", "wind": "", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "スノーラット", "lv": "25", "hp": "14040", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "", "wind": "○", "shine": "", "dark": "○", "area": "エアロス山" }, { "name": "ワイバーン", "lv": "25", "hp": "15000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "ミストラル", "lv": "25", "hp": "14469", "physics": "▲", "devil": "▲", "ground": "▲", "water": "×", "fire": "◎", "wind": "▲", "shine": "", "dark": "○", "area": "エアロス山" }, { "name": "イェティ", "lv": "26", "hp": "15750", "physics": "", "devil": "", "ground": "", "water": "▲", "fire": "○", "wind": "", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "アイスロック", "lv": "26", "hp": "30000", "physics": "▲", "devil": "◎", "ground": "×", "water": "◎", "fire": "◎", "wind": "◎", "shine": "○", "dark": "", "area": "エアロス山" }, { "name": "キュエルワイバーン", "lv": "27", "hp": "16000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "", "dark": "", "area": "エアロス山" }, { "name": "イエティシャーマン", "lv": "27", "hp": "18000", "physics": "", "devil": "", "ground": "", "water": "▲", "fire": "○", "wind": "", "shine": "", "dark": "", "area": "エアロス山" },
    { "name": "マインラット", "lv": "18", "hp": "8448", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "", "wind": "○", "shine": "", "dark": "○", "area": "空中宮殿シャリアン" }, { "name": "バーンピアッサー", "lv": "19", "hp": "8500", "physics": "", "devil": "", "ground": "", "water": "○", "fire": "×", "wind": "", "shine": "", "dark": "", "area": "空中宮殿シャリアン" }, { "name": "ヴィントバッサー", "lv": "23", "hp": "16800", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "×", "shine": "○", "dark": "▲", "area": "空中宮殿シャリアン" }, { "name": "ワイバーン", "lv": "26", "hp": "19000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "", "dark": "", "area": "空中宮殿シャリアン" }, { "name": "ワイバーン", "lv": "27", "hp": "21000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "", "dark": "", "area": "空中宮殿シャリアン" }, { "name": "レフゲシュタ", "lv": "27", "hp": "20000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "空中宮殿シャリアン" }, { "name": "カタクラタラスレン", "lv": "27", "hp": "48000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "○", "dark": "▲", "area": "空中宮殿シャリアン" }, { "name": "レフゲシュタ", "lv": "28", "hp": "21000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "空中宮殿シャリアン" }, { "name": "フリーザー", "lv": "29", "hp": "44352", "physics": "", "devil": "×", "ground": "×", "water": "×", "fire": "○", "wind": "×", "shine": "", "dark": "", "area": "空中宮殿シャリアン" }, { "name": "風竜ウェンディオス", "lv": "30", "hp": "1032000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "", "dark": "", "area": "空中宮殿シャリアン" },
    { "name": "マインラット", "lv": "20", "hp": "8889", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "", "wind": "○", "shine": "", "dark": "○", "area": "ボルゴナ火山島" }, { "name": "シュカルスーファー", "lv": "20", "hp": "9150", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ボルゴナ火山島" }, { "name": "シュカルスーファー", "lv": "21", "hp": "10800", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ボルゴナ火山島" }, { "name": "ヴァイツアーアウト", "lv": "22", "hp": "12600", "physics": "▲", "devil": "▲", "ground": "▲", "water": "◎", "fire": "×", "wind": "▲", "shine": "", "dark": "○", "area": "ボルゴナ火山島" }, { "name": "ヴァイツアーアウト", "lv": "23", "hp": "13050", "physics": "▲", "devil": "▲", "ground": "▲", "water": "◎", "fire": "×", "wind": "▲", "shine": "", "dark": "○", "area": "ボルゴナ火山島" }, { "name": "フラムマッフル", "lv": "24", "hp": "13500", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "ボルゴナ火山島" }, { "name": "ロックスター", "lv": "24", "hp": "14400", "physics": "▲", "devil": "◎", "ground": "×", "water": "◎", "fire": "◎", "wind": "◎", "shine": "○", "dark": "", "area": "ボルゴナ火山島" }, { "name": "シュカルボルゴナ", "lv": "24", "hp": "13443", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ボルゴナ火山島" }, { "name": "フラムボルケン", "lv": "26", "hp": "13950", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "ボルゴナ火山島" },
    { "name": "フラムマッフル", "lv": "25", "hp": "17000", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "炎魔殿" }, { "name": "マグマストマック", "lv": "25", "hp": "15900", "physics": "", "devil": "×", "ground": "×", "water": "×", "fire": "○", "wind": "×", "shine": "", "dark": "", "area": "炎魔殿" }, { "name": "フラムマッフル", "lv": "26", "hp": "19380", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "炎魔殿" }, { "name": "シュカルバーナー", "lv": "26", "hp": "20100", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "炎魔殿" }, { "name": "ロックスター", "lv": "27", "hp": "37000", "physics": "▲", "devil": "◎", "ground": "×", "water": "◎", "fire": "◎", "wind": "◎", "shine": "○", "dark": "", "area": "炎魔殿" }, { "name": "フラムマッフル", "lv": "30", "hp": "29500", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "炎魔殿" }, { "name": "火竜ボルガオラ", "lv": "30", "hp": "1118400", "physics": "", "devil": "", "ground": "", "water": "◎", "fire": "×", "wind": "", "shine": "", "dark": "", "area": "炎魔殿" },
    { "name": "ツーン", "lv": "19", "hp": "7047", "physics": "", "devil": "", "ground": "×", "water": "", "fire": "", "wind": "", "shine": "×", "dark": "◎", "area": "カルハリ砂漠" }, { "name": "スコーピオン", "lv": "19", "hp": "7047", "physics": "", "devil": "", "ground": "", "water": "○", "fire": "×", "wind": "", "shine": "", "dark": "", "area": "カルハリ砂漠" }, { "name": "レザル", "lv": "21", "hp": "8334", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "カルハリ砂漠" }, { "name": "ツンツーン", "lv": "21", "hp": "8334", "physics": "", "devil": "", "ground": "×", "water": "", "fire": "", "wind": "", "shine": "×", "dark": "◎", "area": "カルハリ砂漠" }, { "name": "マージレザル", "lv": "23", "hp": "10428", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "カルハリ砂漠" }, { "name": "レザルチーフ", "lv": "24", "hp": "11520", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "カルハリ砂漠" }, { "name": "ゲシュタ", "lv": "25", "hp": "13887", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "カルハリ砂漠" }, { "name": "アンガーゲシュタ", "lv": "27", "hp": "19116", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "カルハリ砂漠" },
    { "name": "タイニーラット", "lv": "25", "hp": "35904", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "", "wind": "○", "shine": "", "dark": "○", "area": "コルキア大空洞" }, { "name": "マローダーピルッツ", "lv": "26", "hp": "40896", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "○", "wind": "", "shine": "◎", "dark": "×", "area": "コルキア大空洞" }, { "name": "アンバーファンガス", "lv": "27", "hp": "58000", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "○", "wind": "", "shine": "◎", "dark": "×", "area": "コルキア大空洞" }, { "name": "クリスタルシューデル", "lv": "28", "hp": "46080", "physics": "▲", "devil": "▲", "ground": "▲", "water": "×", "fire": "◎", "wind": "▲", "shine": "", "dark": "○", "area": "コルキア大空洞" }, { "name": "マローダーグリーブ", "lv": "28", "hp": "80000", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "○", "wind": "", "shine": "◎", "dark": "×", "area": "コルキア大空洞" }, { "name": "スネアラット", "lv": "29", "hp": "100000", "physics": "", "devil": "", "ground": "▲", "water": "", "fire": "", "wind": "○", "shine": "", "dark": "○", "area": "コルキア大空洞" }, { "name": "トロル", "lv": "30", "hp": "167744", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "コルキア大空洞" }, { "name": "ブルグデレル", "lv": "30", "hp": "146776", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "コルキア大空洞" }, { "name": "ヘルブッチャー", "lv": "30", "hp": "994560", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "コルキア大空洞" },
    { "name": "ガンデルオーグル", "lv": "19", "hp": "9654", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" }, { "name": "ガンデルオーグル", "lv": "20", "hp": "9900", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" }, { "name": "ステイメンオーグル", "lv": "25", "hp": "13275", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" }, { "name": "コーリングオーグル", "lv": "26", "hp": "15819", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" }, { "name": "ステイメンオーグル", "lv": "27", "hp": "17100", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" }, { "name": "コーリングオーグル", "lv": "27", "hp": "17343", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "竜のあぎと" },
    { "name": "アッドスコーピオン", "lv": "20", "hp": "12000", "physics": "", "devil": "", "ground": "", "water": "○", "fire": "×", "wind": "", "shine": "", "dark": "", "area": "地響きの神殿" }, { "name": "レザル", "lv": "23", "hp": "17424", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "地響きの神殿" }, { "name": "ゲシュタ", "lv": "26", "hp": "21092", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "地響きの神殿" }, { "name": "マージレザルチーフ", "lv": "26", "hp": "14688", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "地響きの神殿" }, { "name": "ゲシュタ", "lv": "27", "hp": "23124", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "地響きの神殿" }, { "name": "レザルリーダー", "lv": "28", "hp": "21896", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "地響きの神殿" }, { "name": "レザルカバリスト", "lv": "29", "hp": "110808", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "○", "wind": "▲", "shine": "", "dark": "", "area": "地響きの神殿" }, { "name": "地竜グリズロック", "lv": "30", "hp": "1063680", "physics": "", "devil": "", "ground": "×", "water": "○", "fire": "◎", "wind": "", "shine": "", "dark": "", "area": "地響きの神殿" },
    { "name": "ポーティートゥーン", "lv": "22", "hp": "13440", "physics": "", "devil": "", "ground": "▲", "water": "×", "fire": "◎", "wind": "○", "shine": "", "dark": "", "area": "カルハリ海岸" }, { "name": "ポーティートゥーン", "lv": "23", "hp": "16320", "physics": "", "devil": "", "ground": "▲", "water": "×", "fire": "◎", "wind": "○", "shine": "", "dark": "", "area": "カルハリ海岸" }, { "name": "カルハリフィッシュ", "lv": "25", "hp": "23040", "physics": "", "devil": "", "ground": "", "water": "▲", "fire": "○", "wind": "○", "shine": "", "dark": "", "area": "カルハリ海岸" },
    { "name": "ダークプヨン", "lv": "23", "hp": "21760", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "○", "dark": "▲", "area": "薄闇の異界" }, { "name": "グリーディビースト", "lv": "27", "hp": "48000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "薄闇の異界" }, { "name": "グリーディビーストコーン", "lv": "28", "hp": "54400", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "薄闇の異界" }, { "name": "ソーサリーゲイズ", "lv": "28", "hp": "51200", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "○", "dark": "▲", "area": "薄闇の異界" }, { "name": "シェイドウォーリア", "lv": "28", "hp": "36000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "○", "dark": "▲", "area": "薄闇の異界" }, { "name": "ファントムドレイク", "lv": "28", "hp": "29000", "physics": "", "devil": "", "ground": "◎", "water": "", "fire": "", "wind": "×", "shine": "○", "dark": "▲", "area": "薄闇の異界" }, { "name": "ロックオブダークマター", "lv": "29", "hp": "32000", "physics": "▲", "devil": "◎", "ground": "×", "water": "◎", "fire": "◎", "wind": "◎", "shine": "○", "dark": "", "area": "薄闇の異界" }, { "name": "ダークトロル", "lv": "30", "hp": "50000", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "薄闇の異界" }, { "name": "ダークトロルコマンダー", "lv": "30", "hp": "181248", "physics": "▲", "devil": "", "ground": "", "water": "○", "fire": "", "wind": "", "shine": "", "dark": "", "area": "薄闇の異界" }, { "name": "謎の騎士", "lv": "30", "hp": "134196", "physics": "×", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "", "area": "薄闇の異界" },
    { "name": "ロストホーム", "lv": "23", "hp": "22500", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ダークネスホール" }, { "name": "ダークパール", "lv": "25", "hp": "22440", "physics": "×", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "", "area": "ダークネスホール" }, { "name": "グリード", "lv": "28", "hp": "70000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ダークネスホール" }, { "name": "ネクロチェス", "lv": "28", "hp": "122400", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ダークネスホール" }, { "name": "ブラックメラナイト", "lv": "29", "hp": "60000", "physics": "×", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "", "area": "ダークネスホール" }, { "name": "トワイライトストーカー", "lv": "29", "hp": "55000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ダークネスホール" }, { "name": "グリード", "lv": "29", "hp": "78000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "×", "area": "ダークネスホール" }, { "name": "マグネダイン", "lv": "30", "hp": "192576", "physics": "×", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "◎", "dark": "", "area": "ダークネスホール" }, { "name": "ブラッドストーン", "lv": "30", "hp": "102544", "physics": "", "devil": "", "ground": "", "water": "", "fire": "○", "wind": "", "shine": "", "dark": "", "area": "ダークネスホール" }, { "name": "クライオブエンジェラ", "lv": "30", "hp": "1360000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "○", "dark": "×", "area": "ダークネスホール" }, { "name": "デステンプラー", "lv": "30", "hp": "544000", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "", "wind": "", "shine": "○", "dark": "×", "area": "ダークネスホール" }, { "name": "ダークテンプラー", "lv": "30", "hp": "544000", "physics": "", "devil": "", "ground": "▲", "water": "○", "fire": "", "wind": "", "shine": "○", "dark": "×", "area": "ダークネスホール" }, { "name": "闇竜ガルガンティス", "lv": "30", "hp": "2040000", "physics": "", "devil": "", "ground": "", "water": "", "fire": "", "wind": "", "shine": "○", "dark": "×", "area": "ダークネスホール" }
];