export type SkillTree = {
    otherJobs: string[],
    skills: { [id: string]: Skill }
}

export type Skill = {
    id?: string,
    name: string,
    prev: string | null,
    maxLevel: number,
    maxSkillName: string | null,
    position: "top" | "bottom" | "left" | "right" | "topright" | "topleft" | "bottomright" | "bottomleft",
    isPassive?: boolean,
    isMaxPassive?: boolean,
}

export default {
    "ファイター": {
        otherJobs: ["ガーディアン", "マジックナイト"],
        skills: {
            "スラッシュ": {
                name: "スラッシュ",
                prev: null,
                maxLevel: 5,
                maxSkillName: "滅多斬り",
                position: "topright",
            },
            "破気撃": {
                name: "破気撃",
                prev: "攻撃力+40-1",
                maxLevel: 5,
                maxSkillName: "血獄撃",
                position: "topright",
            },
            "練気斬": {
                name: "練気斬",
                prev: "挑発",
                maxLevel: 5,
                maxSkillName: "魂震練気斬",
                position: "topright",
            },
            "挑発": {
                name: "挑発",
                prev: "スラッシュ",
                maxLevel: 5,
                maxSkillName: "不屈の挑発",
                position: "topright",
            },
            "決闘": {
                name: "決闘",
                prev: "攻撃力+40-3",
                maxLevel: 5,
                maxSkillName: "覇王断",
                position: "topleft",
            },
            "[継承]攻撃力+40-1": {
                name: "[継承]攻撃力+40",
                prev: "挑発",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topleft",
            },
            "[継承]攻撃力+40-2": {
                name: "[継承]攻撃力+40",
                prev: "[継承]攻撃力+40-1",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topleft",
            },
            "攻撃力+40-1": {
                name: "攻撃力+40",
                prev: "スラッシュ",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "bottom",
            },
            "攻撃力+40-2": {
                name: "攻撃力+40",
                prev: "破気撃",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topright",
            },
            "攻撃力+40-3": {
                name: "攻撃力+40",
                prev: "練気斬",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topleft",
            },
            "なぎ払い": {
                name: "なぎ払い",
                prev: "攻撃力+40-2",
                maxLevel: 5,
                maxSkillName: "渾身薙ぎ",
                position: "topright",
            },
            "戦士の心得": {
                name: "戦士の心得",
                prev: null,
                maxLevel: 5,
                maxSkillName: "戦士の誇り",
                isMaxPassive: true,
                position: "topleft",
            },
            "防御のかまえ": {
                name: "防御のかまえ",
                prev: "戦士の心得",
                maxLevel: 5,
                maxSkillName: "熟練の守備",
                isMaxPassive: true,
                position: "bottom",
            },
            "戦う勇気": {
                name: "戦う勇気",
                prev: "戦士の心得",
                maxLevel: 5,
                maxSkillName: "みなぎる闘志",
                position: "topleft",
            },
            "防御力+80-1": {
                name: "防御力+80",
                prev: "戦う勇気",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topleft",
            },
            "防御力+80-2": {
                name: "防御力+80",
                prev: "防御のかまえ",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "topleft",
            },
            "筋骨隆々": {
                name: "筋骨隆々",
                prev: "防御力+80-1",
                maxLevel: 5,
                maxSkillName: "超人化",
                position: "topright",
            },
            "[継承]防御力+80": {
                name: "[継承]防御力+80",
                prev: "防御力+80-1",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "bottom",
            },
            "フィットアーマー": {
                name: "フィットアーマー",
                prev: "防御力+80-2",
                maxLevel: 5,
                maxSkillName: "キングスアーマー",
                position: "left",
            },
            "シールドガード": {
                name: "シールドガード",
                prev: "防御のかまえ",
                maxLevel: 5,
                maxSkillName: "アダマントガード",
                position: "bottomleft",
            },
            "防御力+80-3": {
                name: "防御力+80",
                prev: "シールドガード",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "bottomleft",
            },
            "ガードスタンス": {
                name: "ガードスタンス",
                prev: "防御力+80-3",
                maxLevel: 5,
                maxSkillName: "盾の達人",
                isMaxPassive: true,
                position: "bottomright",
            },
            "[継承]防御効率+2-1": {
                name: "[継承]防御効率+2",
                prev: "防御力+80-3",
                maxLevel: 1,
                maxSkillName: null,
                isPassive: true,
                position: "top",
            },
            "カウンターアタック": {
                name: "カウンターアタック",
                prev: "戦士の心得",
                maxLevel: 5,
                maxSkillName: "マルチカウンター",
                position: "top",
            },
            "クリティカルカウンター": {
                name: "クリティカルカウンター",
                prev: "カウンターアタック",
                maxLevel: 5,
                maxSkillName: "熾烈なる報復",
                position: "topleft",
            },
        }
    },
    "ウィザード": {
        otherJobs: [],
        skills: {
            "ファイア": {
                name: "ファイア",
                prev: null,
                maxLevel: 5,
                maxSkillName: "ヘルファイア",
                position: "top",
            },
            "サンダー": {
                name: "サンダー",
                prev: "ファイア",
                maxLevel: 5,
                maxSkillName: "ヘルサンダー",
                position: "top",
            },
            "フロスト": {
                name: "フロスト",
                prev: "サンダー",
                maxLevel: 5,
                maxSkillName: "ヘルフロスト",
                position: "top",
            },
            "ファイアボルト": {
                name: "ファイアボルト",
                prev: "フロスト",
                maxLevel: 5,
                maxSkillName: "ヘルフレイム",
                position: "bottomleft",
            },
            "サンダーブラスト": {
                name: "サンダーブラスト",
                prev: "ファイアボルト",
                maxLevel: 5,
                maxSkillName: "サンダースコール",
                position: "bottomleft",
            },
            "フロストストライク": {
                name: "フロストストライク",
                prev: "サンダーブラスト",
                maxLevel: 5,
                maxSkillName: "フロストキャノン",
                position: "bottomleft",
            },
            "ブリザード": {
                name: "ブリザード",
                prev: "フロストストライク",
                maxLevel: 5,
                maxSkillName: "アバランチ",
                position: "bottomleft",
            },
            "エクスプロージョン": {
                name: "エクスプロージョン",
                prev: "ブリザード",
                maxLevel: 5,
                maxSkillName: "イグニス・レイジ",
                position: "bottom",
            },
            "サンダーストーム": {
                name: "サンダーストーム",
                prev: "エクスプロージョン",
                maxLevel: 5,
                maxSkillName: "終末の雷嵐",
                position: "bottom",
            },
            "ポイズン": {
                name: "ポイズン",
                prev: null,
                maxLevel: 5,
                maxSkillName: "デッドリーベノム",
                position: "bottomleft",
            },
            "MP+40-1": {
                name: "MP+40-1",
                prev: "ポイズン",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "フリーズ": {
                name: "フリーズ",
                prev: "MP+40-1",
                maxLevel: 5,
                maxSkillName: "フリーズショック",
                position: "bottomleft",
            },
            "[継承]MP+40": {
                name: "[継承]MP+40",
                prev: "フリーズ",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomright",
            },
            "レッサーディスペル": {
                name: "レッサーディスペル",
                prev: "[継承]MP+40",
                maxLevel: 5,
                maxSkillName: "魔素回収",
                position: "bottomright",
            },
            "知力+40-1": {
                name: "知力+40",
                prev: "レッサーディスペル",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomright",
            },
            "[継承]知力+40": {
                name: "[継承]知力+40",
                prev: "知力+40-1",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomright",
            },
            "ディスペル": {
                name: "ディスペル",
                prev: "[継承]知力+40",
                maxLevel: 5,
                maxSkillName: "魔解奪",
                position: "topright",
            },
            "[継承]魔法クリティカル最大倍率+0.1": {
                name: "[継承]魔法クリティカル最大倍率+0.1",
                prev: "ディスペル",
                maxLevel: 1,
                maxSkillName: null,
                position: "topright",
            },
            "術士の心得": {
                name: "術士の心得",
                prev: null,
                maxLevel: 5,
                maxSkillName: "術士の魔力",
                position: "bottomright",
            },
            "MP+40-2": {
                name: "MP+40",
                prev: "術士の心得",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomright",
            },
            "マジックシールド": {
                name: "マジックシールド",
                prev: "MP+40-2",
                maxLevel: 5,
                maxSkillName: "マジックウォール",
                position: "bottomright",
            },
            "知力+40-2": {
                name: "知力+40",
                prev: "マジックシールド",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "導きの光": {
                name: "導きの光",
                prev: "知力+40-2",
                maxLevel: 5,
                maxSkillName: "導師の皆伝",
                position: "top",
            },
            "MP+40-3": {
                name: "MP+40",
                prev: "導きの光",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "知力+40-3": {
                name: "知力+40",
                prev: "MP+40-3",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "[継承]詠唱速度+2": {
                name: "[継承]詠唱速度+2",
                prev: "知力+40-3",
                maxLevel: 1,
                maxSkillName: null,
                position: "topleft",
            },
            "アーケインチャージ": {
                name: "アーケインチャージ",
                prev: "[継承]詠唱速度+2",
                maxLevel: 5,
                maxSkillName: "ハイパーアーケインチャージ",
                position: "topleft",
            },
        }
    },
    "シーフ": {
        otherJobs: ["アサシン", "モンク"],
        skills: {
            "フェイントアタック": {
                name: "フェイントアタック",
                prev: null,
                maxLevel: 5,
                maxSkillName: "殺しの前撃",
                position: "bottomleft",
            },
            "影歩撃": {
                name: "影歩撃",
                prev: "フェイントアタック",
                maxLevel: 5,
                maxSkillName: "影没",
                position: "topleft",
            },
            "攻撃力+40-1": {
                name: "攻撃力+40",
                prev: "影歩撃",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "急所攻撃": {
                name: "急所攻撃",
                prev: "攻撃力+40-1",
                maxLevel: 5,
                maxSkillName: "ハートスキューア",
                position: "top",
            },
            "[継承]攻撃力+40": {
                name: "[継承]攻撃力+40",
                prev: "急所攻撃",
                maxLevel: 1,
                maxSkillName: null,
                position: "topright",
            },
            "魔封撃": {
                name: "魔封撃",
                prev: "影歩撃",
                maxLevel: 5,
                maxSkillName: "術者殺し",
                position: "topright",
            },
            "攻撃力+40-2": {
                name: "攻撃力+40",
                prev: "魔封撃",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "影当身": {
                name: "影当身",
                prev: "攻撃力+40-2",
                maxLevel: 5,
                maxSkillName: "永き眠りへの誘い",
                position: "topright",
            },
            "足がらみ": {
                name: "足がらみ",
                prev: "影当身",
                maxLevel: 5,
                maxSkillName: "アキレスブレイク",
                position: "topright",
            },
            "盗賊の心得": {
                name: "盗賊の心得",
                prev: null,
                maxLevel: 5,
                maxSkillName: "盗賊の見切り",
                position: "right",
            },
            "疾風の陣": {
                name: "疾風の陣",
                prev: "盗賊の心得",
                maxLevel: 5,
                maxSkillName: "砂嵐の陣",
                position: "bottom",
            },
            "速さ+40-1": {
                name: "速さ+40",
                prev: "疾風の陣",
                maxLevel: 1,
                maxSkillName: null,
                position: "topright",
            },
            "[継承]速さ+40": {
                name: "[継承]速さ+40",
                prev: "速さ+40-1",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "[継承]物理クリティカル最大倍率+0.1": {
                name: "[継承]物理クリティカル最大倍率+0.1",
                prev: "速さ+40-1",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottom",
            },
            "速さ+40-2": {
                name: "速さ+40",
                prev: "盗賊の心得",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "盗賊の身かわし": {
                name: "盗賊の身かわし",
                prev: "速さ+40-2",
                maxLevel: 5,
                maxSkillName: "盗賊の身かわし",
                position: "bottom",
            },
            "深く突き立て！": {
                name: "深く突き立て！",
                prev: "盗賊の身かわし",
                maxLevel: 5,
                maxSkillName: "真・深く突き立て！",
                position: "bottomright",
            },
            "速さ+40-3": {
                name: "速さ+40",
                prev: "盗賊の身かわし",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "ラッシュ": {
                name: "ラッシュ",
                prev: "速さ+40-3",
                maxLevel: 5,
                maxSkillName: "アドレナリン・ハイ",
                position: "bottomright",
            },
            "フェイクデス": {
                name: "フェイクデス",
                prev: "速さ+40-2",
                maxLevel: 5,
                maxSkillName: "擬死再生",
                position: "bottomleft",
            },
            "攻撃力+40-3": {
                name: "攻撃力+40",
                prev: "フェイクデス",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "オーラスナッチ": {
                name: "オーラスナッチ",
                prev: "攻撃力+40-3",
                maxLevel: 5,
                maxSkillName: "オーラジャック",
                position: "bottomleft",
            },
            "[継承]器用+40": {
                name: "[継承]器用+40",
                prev: "オーラスナッチ",
                maxLevel: 1,
                maxSkillName: null,
                position: "topleft",
            },
            "追い風": {
                name: "追い風",
                prev: "オーラスナッチ",
                maxLevel: 5,
                maxSkillName: "幸運の風",
                position: "bottomright",
            },
        }
    },
    "クレリック": {
        otherJobs: [],
        skills: {
            "エンゼルフロウ": {
                name: "エンゼルフロウ",
                prev: null,
                maxLevel: 5,
                maxSkillName: "エンゼルブラスト",
                position: "bottom",
            },
            "ホーリーブロウ": {
                name: "ホーリーブロウ",
                prev: "エンゼルフロウ",
                maxLevel: 5,
                maxSkillName: "聖なる裁撃",
                position: "topright",
            },
            "攻撃力+40-1": {
                name: "攻撃力+40",
                prev: "ホーリーブロウ",
                maxLevel: 1,
                maxSkillName: null,
                position: "topright",
            },
            "ホーリースマイト": {
                name: "ホーリースマイト",
                prev: "攻撃力+40-1",
                maxLevel: 5,
                maxSkillName: "正義の暴打",
                position: "bottom",
            },
            "[継承]攻撃力+40": {
                name: "[継承]攻撃力+40",
                prev: "ホーリースマイト",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "まやかしの光": {
                name: "まやかしの光",
                prev: "エンゼルフロウ",
                maxLevel: 5,
                maxSkillName: "堕落の光",
                position: "topleft",
            },
            "知力+40-1": {
                name: "知力+40",
                prev: "まやかしの光",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "サイレンス": {
                name: "サイレンス",
                prev: "知力+40-1",
                maxLevel: 5,
                maxSkillName: "封心鎮圧",
                position: "bottomright",
            },
            "平和な心": {
                name: "平和な心",
                prev: "サイレンス",
                maxLevel: 5,
                maxSkillName: "悔根の心",
                position: "bottomright",
            },
            "神官の心得": {
                name: "神官の心得",
                prev: null,
                maxLevel: 5,
                maxSkillName: "神官の永誓",
                position: "topleft",
            },
            "防御力+80-1": {
                name: "防御力+80",
                prev: "神官の心得",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "慈悲の心": {
                name: "慈悲の心",
                prev: "防御力+80-1",
                maxLevel: 5,
                maxSkillName: "深き慈悲の保護",
                position: "topleft",
            },
            "HP+40-1": {
                name: "HP+40",
                prev: "慈悲の心",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomleft",
            },
            "守護の泡": {
                name: "守護の泡",
                prev: "HP+40-1",
                maxLevel: 5,
                maxSkillName: "守護の泡壁",
                position: "bottomleft",
            },
            "[継承]MP+40": {
                name: "[継承]MP+40",
                prev: "守護の泡",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottom",
            },
            "七色の守護の泡": {
                name: "七色の守護の泡",
                prev: "[継承]MP+40",
                maxLevel: 5,
                maxSkillName: "金剛の大泡",
                position: "bottomright",
            },
            "慈悲の博愛": {
                name: "慈悲の博愛",
                prev: "[継承]MP+40",
                maxLevel: 5,
                maxSkillName: "慈愛の奇蹟",
                position: "right",
            },
            "クルセイド": {
                name: "クルセイド",
                prev: "[継承]MP+40",
                maxLevel: 5,
                maxSkillName: "高速クルセイド",
                position: "bottom",
            },
            "セルフヒール": {
                name: "セルフヒール",
                prev: null,
                maxLevel: 5,
                maxSkillName: "リフレッシュセルフ",
                position: "topright",
            },
            "精神+40-1": {
                name: "精神+40",
                prev: "セルフヒール",
                maxLevel: 1,
                maxSkillName: null,
                position: "top",
            },
            "ヒール": {
                name: "ヒール",
                prev: "精神+40-1",
                maxLevel: 5,
                maxSkillName: "リニュウヒール",
                position: "topright",
            },
            "キュアポイズン": {
                name: "キュアポイズン",
                prev: "ヒール",
                maxLevel: 5,
                maxSkillName: "マスキュアポイズン",
                position: "bottomright",
            },
            "MP+40-1": {
                name: "MP+40",
                prev: "キュアポイズン",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottomright",
            },
            "[継承]精神+40": {
                name: "[継承]精神+40",
                prev: "MP+40-1",
                maxLevel: 1,
                maxSkillName: null,
                position: "bottom",
            },
            "リバティ": {
                name: "リバティ",
                prev: "[継承]精神+40",
                maxLevel: 5,
                maxSkillName: "マスリバティ",
                position: "left",
            },
            "グループヒール": {
                name: "グループヒール",
                prev: "[継承]精神+40",
                maxLevel: 5,
                maxSkillName: "分け隔て無き治癒",
                position: "bottom",
            },
        }
    },
    "ガーディアン": {
        otherJobs: [],
        skills: {
            "突撃": { name: "突撃", prev: null, maxLevel: 5, maxSkillName: "ギガントクラッシュ", position: "bottom", },
            "咆哮": { name: "咆哮", prev: "HP+40-1", maxLevel: 5, maxSkillName: "鋼の咆哮", position: "top", },
            "鉄壁のかまえ": { name: "鉄壁のかまえ", prev: null, maxLevel: 5, maxSkillName: "大盾のかまえ", position: "bottomleft", },
            "城壁の陣": { name: "城壁の陣", prev: "防御力+80-1", maxLevel: 5, maxSkillName: "大岩の陣", position: "bottomleft", },
            "ランサーニードル": { name: "ランサーニードル", prev: "突撃", maxLevel: 5, maxSkillName: "ランサーインパクト", position: "bottom", },
            "パイルバンカー": { name: "パイルバンカー", prev: "ランサーニードル", maxLevel: 5, maxSkillName: "衝点突", position: "bottom", },
            "身代わり": { name: "身代わり", prev: "戦の叫び", maxLevel: 5, maxSkillName: "不退転の護衛", position: "bottomleft", },
            "気合防御": { name: "気合防御", prev: "防御力+80-2", maxLevel: 5, maxSkillName: "屈強なる肉の巨壁", position: "top", },
            "戦の叫び": { name: "戦の叫び", prev: "咆哮", maxLevel: 5, maxSkillName: "戦慄の叫び", position: "left", },
            "大城壁の陣": { name: "大城壁の陣", prev: "防御力+80-3", maxLevel: 5, maxSkillName: "不沈城の大陣", position: "bottomright", },
            "パイルスラスト": { name: "パイルスラスト", prev: "パイルバンカー", maxLevel: 5, maxSkillName: "弩級肉弾撃", position: "topright", },
            "一心盾": { name: "一心盾", prev: "HP+40-3", maxLevel: 5, maxSkillName: "真なる盾守", position: "bottomright", },
            "猛き雄叫び": { name: "猛き雄叫び", prev: "身代わり", maxLevel: 5, maxSkillName: "勝ち鬨の雄叫び", position: "right", },
            "不動の大盾": { name: "不動の大盾", prev: "[継承]防御力+80", maxLevel: 5, maxSkillName: "重盾の衝撃", position: "top", },
            "ガードカウンター": { name: "ガードカウンター", prev: "咆哮", maxLevel: 5, maxSkillName: "マルチガードカウンター", position: "right", },
            "ヘヴィーカウンター": { name: "ヘヴィーカウンター", prev: "ガードカウンター", maxLevel: 5, maxSkillName: "コロッサスカウンター", position: "bottomright", },
            "盾を掲げよ！": { name: "盾を掲げよ！", prev: "HP+40-2", maxLevel: 5, maxSkillName: "鎧とひとつに！", position: "bottomleft", },
            "[継承]防御力+80": { name: "[継承]防御力+80", prev: "[継承]HP+40", maxLevel: 1, maxSkillName: null, position: "top", },
            "[継承]HP+40": { name: "[継承]HP+40", prev: "一心盾", maxLevel: 1, maxSkillName: null, position: "bottomright", },
            "[継承]防御効率+2": { name: "[継承]防御効率+2", prev: "ヘヴィーカウンター", maxLevel: 1, maxSkillName: null, position: "left", },
            "HP+40-1": { name: "HP+40", prev: null, maxLevel: 1, maxSkillName: null, position: "top", },
            "HP+40-2": { name: "HP+40", prev: "[継承]HP+40", maxLevel: 1, maxSkillName: null, position: "bottomleft", },
            "HP+40-3": { name: "HP+40", prev: null, maxLevel: 1, maxSkillName: null, position: "bottomright", },
            "防御力+80-1": { name: "防御力+80", prev: "鉄壁のかまえ", maxLevel: 1, maxSkillName: null, position: "bottomleft", },
            "防御力+80-2": { name: "防御力+80", prev: "城壁の陣", maxLevel: 1, maxSkillName: null, position: "top", },
            "防御力+80-3": { name: "防御力+80", prev: "城壁の陣", maxLevel: 1, maxSkillName: null, position: "bottomright", },
        },
    },
    "マジックナイト": {
        otherJobs: [],
        skills: {
            'マジカルバックラー': { name: 'マジカルバックラー', prev: null, maxLevel: 5, maxSkillName: 'マジカルガーダー', position: 'bottomleft', },
            'ファイアーアロー': { name: 'ファイアーアロー', prev: null, maxLevel: 5, maxSkillName: 'メルトアロー', position: 'topleft', },
            'サンダーアロー': { name: 'サンダーアロー', prev: 'MP+40-1', maxLevel: 5, maxSkillName: 'インパルスアロー', position: 'topright', },
            'フロストアロー': { name: 'フロストアロー', prev: 'トリックビジョン', maxLevel: 5, maxSkillName: 'アシッドアロー', position: 'right', },
            '炎の守り': { name: '炎の守り', prev: 'ファイアーアロー', maxLevel: 5, maxSkillName: '炎の精霊の加護', position: 'topleft', },
            '風の守り': { name: '風の守り', prev: 'サンダーアロー', maxLevel: 5, maxSkillName: '風の精霊の加護', position: 'right', },
            '水の守り': { name: '水の守り', prev: 'フロストアロー', maxLevel: 5, maxSkillName: '水の精霊の加護', position: 'bottom', },
            '大地の守り': { name: '大地の守り', prev: 'コンシューム オーラ', maxLevel: 5, maxSkillName: '大地の精霊の加護', position: 'bottomright', },
            'マジックウェイブ': { name: 'マジックウェイブ', prev: '知力+40-2', maxLevel: 5, maxSkillName: 'ブレイクウェイブ', position: 'top', },
            'マジックサージ': { name: 'マジックサージ', prev: '風の守り', maxLevel: 5, maxSkillName: 'マジックサイフォン', position: 'top', },
            'トリックビジョン': { name: 'トリックビジョン', prev: 'HP+40-1', maxLevel: 5, maxSkillName: 'トリックフィールド', position: 'bottomright', },
            'マジックスラスト': { name: 'マジックスラスト', prev: '[継承]MP+40', maxLevel: 5, maxSkillName: '双穴突貫衝', position: 'topleft', },
            '鈍呪刺突': { name: '鈍呪刺突', prev: '知力+40-1', maxLevel: 5, maxSkillName: '絶命超突窮', position: 'bottomleft', },
            'コンシューム オーラ': { name: 'コンシューム オーラ', prev: '[継承]防御力+80', maxLevel: 5, maxSkillName: 'オーラ キュイジーヌ', position: 'bottom', },
            'マジカルブレイド': { name: 'マジカルブレイド', prev: '[継承]HP+40', maxLevel: 5, maxSkillName: 'ゾディアックブレイド', position: 'topright', },
            '[継承]防御力+80': { name: '[継承]防御力+80', prev: '防御力+80-1', maxLevel: 1, maxSkillName: null, position: 'left', },
            '[継承]MP+40': { name: '[継承]MP+40', prev: 'マジックサージ', maxLevel: 1, maxSkillName: null, position: 'topleft', },
            '[継承]HP+40': { name: '[継承]HP+40', prev: 'マジックウェイブ', maxLevel: 1, maxSkillName: null, position: 'topright', },
            '[継承]四属性耐性+5': { name: '[継承]四属性耐性+5', prev: '大地の守り', maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            '知力+40-1': { name: '知力+40', prev: '水の守り', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '防御力+80-1': { name: '防御力+80', prev: 'マジカルバックラー', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '攻撃力+40-1': { name: '攻撃力+40', prev: '炎の守り', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            'HP+40-1': { name: 'HP+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            'MP+40-1': { name: 'MP+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'topright', },
            '知力+40-2': { name: '知力+40', prev: '攻撃力+40-1', maxLevel: 1, maxSkillName: null, position: 'top', },
        },
    },
    "ウォーロック": {
        otherJobs: [],
        skills: {
            'ドレイン': { name: 'ドレイン', prev: null, maxLevel: 5, maxSkillName: 'マインドドレイン', position: 'topright', },
            '闇の福音': { name: '闇の福音', prev: '知力+40-1', maxLevel: 5, maxSkillName: '闇への回帰', position: 'topleft', },
            '死神の衣': { name: '死神の衣', prev: '闇の福音', maxLevel: 5, maxSkillName: '死神の法衣', position: 'top', },
            'アーマーブレイク': { name: 'アーマーブレイク', prev: '精神+40-1', maxLevel: 5, maxSkillName: 'アーマーコラプス', position: 'bottomleft', },
            'アイスブレス': { name: 'アイスブレス', prev: 'MP+40-1', maxLevel: 5, maxSkillName: 'アイスカース', position: 'top', },
            'メガドレイン': { name: 'メガドレイン', prev: 'ドレイン', maxLevel: 5, maxSkillName: '生命枯渇魔法', position: 'topright', },
            'ソードブレイク': { name: 'ソードブレイク', prev: 'ドリームフォール', maxLevel: 5, maxSkillName: 'ソードコラプス', position: 'bottomright', },
            'アイスブレイズ': { name: 'アイスブレイズ', prev: 'アイスブレス', maxLevel: 5, maxSkillName: 'アイスヘックス', position: 'topleft', },
            'サンダーブレイク': { name: 'サンダーブレイク', prev: 'アイスブレス', maxLevel: 5, maxSkillName: '双雷爆', position: 'topright', },
            'ドリームフォール': { name: 'ドリームフォール', prev: 'アーマーブレイク', maxLevel: 5, maxSkillName: 'ドリームトリップ', position: 'bottomleft', },
            'ブレイクアームズ': { name: 'ブレイクアームズ', prev: 'ソードブレイク', maxLevel: 5, maxSkillName: 'ディケイドアームズ', position: 'right', },
            'ギガドレイン': { name: 'ギガドレイン', prev: 'メガドレイン', maxLevel: 5, maxSkillName: 'ダークネスドレイン', position: 'topright', },
            '黒猫の呪い': { name: '黒猫の呪い', prev: 'HP+40-1', maxLevel: 5, maxSkillName: '虐戯・黒猫の魂舐め', position: 'topright', },
            '粘つくスライム酸': { name: '粘つくスライム酸', prev: 'ソードブレイク', maxLevel: 5, maxSkillName: '虐戯・スライム溶解酸', position: 'topright', },
            '[継承]精神+40': { name: '[継承]精神+40', prev: 'メガドレイン', maxLevel: 1, maxSkillName: null, position: 'right', },
            '[継承]MP+40': { name: '[継承]MP+40', prev: 'アイスブレス', maxLevel: 1, maxSkillName: null, position: 'top', },
            '[継承]知力+40': { name: '[継承]知力+40', prev: '闇の福音', maxLevel: 1, maxSkillName: null, position: 'left', },
            '[継承]HP+40': { name: '[継承]HP+40', prev: 'メガドレイン', maxLevel: 1, maxSkillName: null, position: 'top', },
            '知力+40-1': { name: '知力+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'topleft', },
            '精神+40-1': { name: '精神+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            'HP+40-1': { name: 'HP+40', prev: 'MP+40-2', maxLevel: 1, maxSkillName: null, position: 'topright', },
            'MP+40-1': { name: 'MP+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'top', },
            'MP+40-2': { name: 'MP+40', prev: 'ドリームフォール', maxLevel: 1, maxSkillName: null, position: 'right', },
            '知力+40-2': { name: '知力+40', prev: '闇の福音', maxLevel: 1, maxSkillName: null, position: 'topleft', },
        },
    },
    "アサシン": {
        otherJobs: [],
        skills: {
            '精神集中': { name: '精神集中', prev: null, maxLevel: 5, maxSkillName: '魔導眼', position: 'bottomright', },
            '催眠波': { name: '催眠波', prev: null, maxLevel: 5, maxSkillName: '催眠連波', position: 'bottomleft', },
            '毒手': { name: '毒手', prev: '器用+40-1', maxLevel: 5, maxSkillName: '猛毒手', position: 'bottom', },
            '必殺の極意': { name: '必殺の極意', prev: '攻撃力+40-2', maxLevel: 5, maxSkillName: '皆殺しの誓い', position: 'bottom', },
            '兜割り': { name: '兜割り', prev: '器用+40-2', maxLevel: 5, maxSkillName: '闇の恐慌', position: 'top', },
            '黒龍閃': { name: '黒龍閃', prev: '攻撃力+40-1', maxLevel: 5, maxSkillName: '黒龍牙撃', position: 'top', },
            '吹き矢': { name: '吹き矢', prev: '兜割り', maxLevel: 5, maxSkillName: '猛毒の吹き矢', position: 'top', },
            '黒龍滅波': { name: '黒龍滅波', prev: '知力+40-2', maxLevel: 5, maxSkillName: '黒龍影伏波', position: 'bottomleft', },
            '闇の衣': { name: '闇の衣', prev: '必殺の極意', maxLevel: 5, maxSkillName: '闇の帳', position: 'topright', },
            '影斬り': { name: '影斬り', prev: '[継承]攻撃力+40', maxLevel: 5, maxSkillName: '大影切断', position: 'bottomright', },
            '死神の眼': { name: '死神の眼', prev: '[継承]速さ+40', maxLevel: 5, maxSkillName: '死神の殺意', position: 'top', },
            '黒龍双咬斬': { name: '黒龍双咬斬', prev: '黒龍滅波', maxLevel: 5, maxSkillName: '黒龍闇殺葬', position: 'bottomleft', },
            '死神の爪': { name: '死神の爪', prev: '死神の眼', maxLevel: 5, maxSkillName: '死神の鋭爪', position: 'top', },
            '[継承]速さ+40': { name: '[継承]速さ+40', prev: '闇の衣', maxLevel: 1, maxSkillName: null, position: 'top', },
            '[継承]攻撃力+40': { name: '[継承]攻撃力+40', prev: '知力+40-2', maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            '[継承]器用+40': { name: '[継承]器用+40', prev: '知力+40-1', maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '[継承]知力+40': { name: '[継承]知力+40', prev: '吹き矢', maxLevel: 1, maxSkillName: null, position: 'top', },
            '攻撃力+40-1': { name: '攻撃力+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'top', },
            '知力+40-1': { name: '知力+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '器用+40-1': { name: '器用+40', prev: '催眠波', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '器用+40-2': { name: '器用+40', prev: '毒手', maxLevel: 1, maxSkillName: null, position: 'topleft', },
            '攻撃力+40-2': { name: '攻撃力+40', prev: '精神集中', maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            '知力+40-2': { name: '知力+40', prev: '黒龍閃', maxLevel: 1, maxSkillName: null, position: 'top', },
        },
    },
    "ビショップ": {
        otherJobs: [],
        skills: {
            'ヒーリング': { name: 'ヒーリング', prev: null, maxLevel: 5, maxSkillName: 'ハイヒーリング', position: 'topleft', },
            'ホーリーアロー': { name: 'ホーリーアロー', prev: '知力+40-1', maxLevel: 5, maxSkillName: '破戒 ブラッドアロー', position: 'bottomleft', },
            'プロテクション': { name: 'プロテクション', prev: 'HP+40-1', maxLevel: 5, maxSkillName: 'ソマト プロテクター', position: 'topright', },
            'キュアサイレンス': { name: 'キュアサイレンス', prev: null, maxLevel: 5, maxSkillName: '秘儀の聖域', position: 'bottom', },
            'ディバインアロー': { name: 'ディバインアロー', prev: 'グリムケージ', maxLevel: 5, maxSkillName: '破戒 コラプトアロー', position: 'top', },
            'バイタルガード': { name: 'バイタルガード', prev: 'MP+40-1', maxLevel: 5, maxSkillName: 'バイタルブースト', position: 'topright', },
            '蘇生': { name: '蘇生', prev: '[継承]精神+40', maxLevel: 5, maxSkillName: '復活の聖刻', position: 'bottomright', },
            'ワイドヒール': { name: 'ワイドヒール', prev: 'セルフリカバー', maxLevel: 5, maxSkillName: 'グレートワイドヒール', position: 'topright', },
            'セルフリカバー': { name: 'セルフリカバー', prev: '[継承]MP+40', maxLevel: 5, maxSkillName: 'マインドリフレッシュ', position: 'topright', },
            'グリムケージ': { name: 'グリムケージ', prev: '知力+40-2', maxLevel: 5, maxSkillName: '破戒 ダークプリズン', position: 'bottomleft', },
            'フラッシュヒール': { name: 'フラッシュヒール', prev: 'ワイドヒール', maxLevel: 5, maxSkillName: '破戒 インスタントラブ', position: 'bottomright', },
            '再生の風': { name: '再生の風', prev: 'フラッシュヒール', maxLevel: 5, maxSkillName: 'ライフストリーム', position: 'bottomright', },
            '修復の輝き': { name: '修復の輝き', prev: '[継承]知力+40', maxLevel: 5, maxSkillName: '修復のオーラ', position: 'bottom', },
            '膨らむ魂の器': { name: '膨らむ魂の器', prev: 'バイタルガード', maxLevel: 5, maxSkillName: '生命の樹', position: 'bottom', },
            '[継承]精神+40': { name: '[継承]精神+40', prev: '精神+40-2', maxLevel: 1, maxSkillName: null, position: 'topright', },
            '[継承]MP+40': { name: '[継承]MP+40', prev: 'ヒーリング', maxLevel: 1, maxSkillName: null, position: 'topleft', },
            '[継承]知力+40': { name: '[継承]知力+40', prev: 'キュアサイレンス', maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '[継承]HP+40': { name: '[継承]HP+40', prev: '再生の風', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '精神+40-1': { name: '精神+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'top', },
            '知力+40-1': { name: '知力+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            'HP+40-1': { name: 'HP+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            'MP+40-1': { name: 'MP+40', prev: 'プロテクション', maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '知力+40-2': { name: '知力+40', prev: 'ホーリーアロー', maxLevel: 1, maxSkillName: null, position: 'top', },
            '精神+40-2': { name: '精神+40', prev: "精神+40-1", maxLevel: 1, maxSkillName: null, position: 'topleft', },
        },
    },
    "モンク": {
        otherJobs: [],
        skills: {
            '瞑想': { name: '瞑想', prev: null, maxLevel: 5, maxSkillName: 'チャクラ精練', position: 'topleft', },
            '天のかまえ': { name: '天のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '共天一体', position: 'top', },
            '気功': { name: '気功', prev: '精神+40-1', maxLevel: 5, maxSkillName: '錬精気功', position: 'topright', },
            '地のかまえ': { name: '地のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '共地一体', position: 'topleft', },
            '鉄拳': { name: '鉄拳', prev: null, maxLevel: 5, maxSkillName: '金剛拳', position: 'bottomright', },
            '人のかまえ': { name: '人のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '共人一体', position: 'left', },
            '虎砲': { name: '虎砲', prev: 'MP+40-1', maxLevel: 5, maxSkillName: '猛虎砲', position: 'bottom', },
            '幽隔': { name: '幽隔', prev: 'HP+40-1', maxLevel: 5, maxSkillName: '世離浮虚', position: 'bottom', },
            '鋼の意思': { name: '鋼の意思', prev: '[継承]HP+40', maxLevel: 5, maxSkillName: '鋼の魂', position: 'right', },
            '気脈掌': { name: '気脈掌', prev: '気功', maxLevel: 5, maxSkillName: '気脈天泉掌', position: 'bottomright', },
            '聖魔群狼拳': { name: '聖魔群狼拳', prev: '[継承]MP+40', maxLevel: 5, maxSkillName: '魔狼千牙拳', position: 'bottomleft', },
            '玄武のかまえ': { name: '玄武のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '玄武鏡鳴', position: 'bottomleft', },
            '青龍のかまえ': { name: '青龍のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '青龍鏡鳴', position: 'bottom', },
            '朱雀のかまえ': { name: '朱雀のかまえ', prev: '器用+40-1', maxLevel: 5, maxSkillName: '朱雀鏡鳴', position: 'bottomright', },
            '[継承]HP+40': { name: '[継承]HP+40', prev: '幽隔', maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '[継承]MP+40': { name: '[継承]MP+40', prev: '虎砲', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '[継承]精神+40': { name: '[継承]精神+40', prev: '気脈掌', maxLevel: 1, maxSkillName: null, position: 'bottom', },
            '[継承]状態異常耐性+5': { name: '[継承]状態異常耐性+5', prev: '鋼の意思', maxLevel: 1, maxSkillName: null, position: 'top', },
            '精神+40-1': { name: '精神+40', prev: '瞑想', maxLevel: 1, maxSkillName: null, position: 'top', },
            '速さ+40-1': { name: '速さ+40', prev: null, maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            '器用+40-1': { name: '器用+40', prev: '速さ+40-1', maxLevel: 1, maxSkillName: null, position: 'bottomleft', },
            'MP+40-1': { name: 'MP+40', prev: '攻撃力+40-1', maxLevel: 1, maxSkillName: null, position: 'right', },
            'HP+40-1': { name: 'HP+40', prev: '速さ+40-1', maxLevel: 1, maxSkillName: null, position: 'bottomright', },
            '攻撃力+40-1': { name: '攻撃力+40', prev: '鉄拳', maxLevel: 1, maxSkillName: null, position: 'bottomright', },
        },
    },
} as { [job: string]: SkillTree }